#!/usr/bin/env python3
"""
Script to combine 8 missing English lesson migration files into a single migration.
This generates a combined SQL file that inserts all missing lessons at once.
"""

import os

# Define the migration files to combine (in order)
MIGRATION_FILES = [
    "019_create_english_a1_family_relationships_lesson.sql",
    "021_create_english_a1_home_describing_places_lesson.sql",
    "023_create_english_a1_daily_routines_actions_lesson.sql",
    "026_create_english_a1_descriptions_lesson.sql",
    "029_create_english_a1_food_drink_ordering_lesson.sql",
    "031_create_english_a1_shopping_prices_lesson.sql",
    "033_create_english_a2_narration_time_lesson.sql",
    "038_create_english_a2_social_functional_language_lesson.sql",
]

def combine_migrations():
    """Combine all migration files into a single SQL file."""
    
    # Get the script directory and migrations directory
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    migrations_dir = os.path.join(project_root, "supabase", "migrations")
    output_file = os.path.join(migrations_dir, "040_insert_missing_english_lessons.sql")
    
    # Header
    combined_sql = """-- Combined Migration: Insert 8 Missing English Lessons
-- This migration inserts the 6 missing A1 lessons and 2 A2 lessons
-- Generated by: scripts/combine_missing_lesson_migrations.py
-- Run this in Supabase SQL Editor to add all missing lessons at once

"""
    
    # Combine each migration file
    for i, migration_file in enumerate(MIGRATION_FILES, start=1):
        file_path = os.path.join(migrations_dir, migration_file)
        
        if not os.path.exists(file_path):
            print(f"WARNING: File not found: {migration_file}")
            continue
        
        # Extract lesson info from filename
        lesson_num = migration_file.split('_')[0]
        lesson_name = migration_file.replace('_create_english_', '').replace('_lesson.sql', '')
        
        combined_sql += f"""
-- ============================================
-- LESSON {i}: {lesson_name.replace('_', ' ').title()}
-- Migration file: {migration_file}
-- ============================================

"""
        
        # Read and append the migration file content
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
            
            # Remove any existing comments about being standalone
            content = content.replace('-- A1 English Lesson:', f'-- Lesson {i}:')
            content = content.replace('-- A2 English Lesson:', f'-- Lesson {i}:')
            
            combined_sql += content
            combined_sql += "\n\n"
    
    # Write the combined file
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(combined_sql)
    
    print(f"✅ Combined migration created: {output_file}")
    print(f"   Combined {len(MIGRATION_FILES)} migration files")
    print(f"   File size: {len(combined_sql)} characters")

if __name__ == "__main__":
    combine_migrations()

